#!/bin/bash

database="DB.txt"

read -p "팀원의 이름을 입력하세요: " search_name


found_info=$(grep -i "^$search_name:" "$database")

if [ -n "$found_info" ]; then
  echo "$found_info"
else
  echo "검색된 팀원이 없습니다."
fi

